version: "2.1"

volumes:
  dispenser:

services:
  dispenser:
    build: ./dispenser
    container_name: "dispenser"
    restart: "no"
    privileged: true
    labels:
      io.balena.features.supervisor-api: 1
