version: "2.1"

volumes:
  dispenser:

services:
  dispenser:
    build: ./dispenser
    container_name: "dispenser"
    restart: "unless-stopped"
    privileged: true
    ports:
      - 5000:5000
    labels:
      io.balena.features.supervisor-api: 1
