version: "2.1"

volumes:
  pictures:

services:
  pet-food-dispenser:
    build: ./dispenser
    container_name: "food-dispenser"
    restart: "unless-stopped"
    privileged: true
    volumes:
      - pictures:/pictures
    ports:
      - "80:80"
    labels:
      io.balena.features.supervisor-api: 1
