FROM balenalib/%%BALENA_MACHINE_NAME%%-python:latest-build
ENV UDEV=on
ENV EMULATED=1

WORKDIR /usr/app

COPY ./requirements.txt .
COPY ./src/. ./src/

# RUN install_packages libgl1-mesa-glx python3-opencv
RUN pip3 install -r requirements.txt

WORKDIR /usr/app/src
# CMD ["python3", "run.py"]
CMD ["gunicorn", "--bind", "0.0.0.0:80", "-w", "1", "run:app"]